version: '3.2'
services:
  antmedia:
    container_name: antmedia-dev
    image: antmedia:dev
    cap_add:
      - "DAC_READ_SEARCH"
    build:
      context: .
      args:
        AntMediaServer: "ant-media-server-1.9.1-community-1.9.1-20200112_1622.zip"
    ports:
      - "5443:5443"
      - "1935:1935"
      - "5080:5080"
